spring.application.name=Popcorn-Pal
spring.datasource.url= jdbc:postgresql://caboose.proxy.rlwy.net:14521/railway
spring.datasource.username= postgres
spring.datasource.password= OophFAnOkGkZitKAdNFhFsanZetfxihh
spring.thymeleaf.cache = false

tmdb.api.key= ec0e9ec87809bf77dbbe98c171b19b39
frontend.url = https://popcornpal210.netlify.app
logging.level.org.springframework.security=DEBUG
jwt.secret.key = li2O6W4XnVFco/0Cnvx92rRg0I8KRPnCGAJa84REA+U=
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true